# Generated by Django 5.2.8 on 2025-12-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_id', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('event_date', models.CharField(blank=True, max_length=100)),
                ('event_time', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('image', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
